export const MOCK_INGREDIENTS = [
  '1 percent milk',
  '95 percent lean ground beef',
  'allspice',
  'almond extract',
  'almond meal',
  'almond milk',
  'almonds',
  'apple',
  'applesauce',
  'applewood smoked bacon',
  'artificial vanilla',
  'asiago cheese',
  'asparagus',
  'avocado',
  'baby spinach',
  'bakers white chocolate',
  'baking mix',
  'baking powder',
  'baking soda',
  'balsamic vinegar',
  'banana',
  'bay leaves',
  'beef',
  'beef bouillon cube',
  'beef broth',
  'beef gravy',
  'bell pepper',
  'berries',
  'black bean sauce',
  'black beans',
  'black pepper',
  'blueberries',
  'boneless beef short ribs',
  'boneless skinless chicken breast',
  'boneless turkey breast',
  'bran',
  'breadcrumbs',
  'broccoli',
  'broccoli florets',
  'butter',
  'buttermilk',
  'butterscotch chips',
  'butterscotch pudding',
  'cabbage',
  'cacao powder',
  'canadian bacon',
  'candied ginger',
  'candied orange peel',
  'candy coated chocolate pieces',
  'candy corn',
  'canned black beans',
  'canned blackeyed peas',
  'canned butter beans',
  'canned diced tomatoes',
  'canned kidney beans',
  'canned pinto beans',
  'canned pumpkin',
  'canned tomato sauce',
  'canned tomatoes',
  'canned white beans',
  'caramel sauce',
  'caraway seeds',
  'carrot',
  'cauliflower',
  'celery',
  'celery salt',
  'celery seed',
  'celery sticks',
  'cheddar cheese',
  'cheese',
  'cherries',
  'cherry tomato',
  'chia seeds',
  'chicken breast',
  'chicken broth',
  'chicken sausage',
  'chicken stock',
  'chicken wings',
  'chili pepper',
  'chili powder',
  'chives',
  'chocolate crumb crust',
  'chocolate hazelnut spread',
  'cilantro',
  'cinnamon',
  'coarse salt',
  'coarse sea salt',
  'cocoa nibs',
  'coconut',
  'coconut flour',
  'coconut milk',
  'coconut oil',
  'condensed cream of chicken soup',
  'condensed cream of mushroom soup',
  'cooked bacon',
  'cooked chicken breast',
  'cooked quinoa',
  'cooked rice',
  'cooked rolled oats',
  'cooking oil',
  'corn',
  'corn kernels',
  'corn starch',
  'corn syrup',
  'corn tortilla chips',
  'cornmeal',
  'cottage cheese',
  'cream',
  'cream cheese',
  'cream of tartar',
  'creamy peanut butter',
  'creole mustard',
  'crimini mushrooms',
  'crushed tomatoes',
  'cumin',
  'dark brown sugar',
  'dark chocolate',
  'dark chocolate bar',
  'dark sesame oil',
  'diced ham',
  'diced tomatoes with green chilies',
  'dill',
  'distilled white vinegar',
  'dried arbol chile',
  'dried basil',
  'dried parsley',
  'dried strawberries',
  'dried thyme',
  'dry yeast',
  'egg',
  'egg noodles',
  'egg whites',
  'egg yolk',
  'elbow macaroni',
  'english muffin',
  'evaporated milk',
  'extra firm tofu',
  'extra virgin olive oil',
  'fat free greek yogurt',
  'fat free milk',
  'feta cheese',
  'filo pastry',
  'finely crushed pretzels',
  'fire roasted tomatoes',
  'flour tortilla',
  'fontina cheese',
  'freeze dried strawberries',
  'fresh basil',
  'fresh mushrooms',
  'garlic',
  'garlic powder',
  'gelatin',
  'ginger',
  'ginger powder',
  'gluten free chocolate sandwich cookies',
  'goat cheese',
  'golden brown sugar',
  'gorgonzola',
  'gouda',
  'graham cracker crumbs',
  'graham crackers',
  'grape tomato',
  'greek yogurt',
  'green beans',
  'green chili pepper',
  'green enchilada sauce',
  'green pepper',
  'green tea bag',
  'ground cayenne pepper',
  'ground chuck',
  'ground cinnamon',
  'ground clove',
  'ground coriander',
  'ground flaxseed',
  'ground pork sausage',
  'gruyere',
  'half and half',
  'ham',
  'harissa',
  'havarti',
  'hemp milk',
  'hersheys kisses brand milk chocolates',
  'hollandaise sauce',
  'hollandaise sauce mix',
  'honey',
  'hot sauce',
  'ice',
  'icing',
  'imitation crab',
  'instant coffee',
  'instant potatoes flakes',
  'instant vanilla pudding mix',
  'italian sausage',
  'italian seasoning',
  'italian tomato',
  'jalapeno pepper',
  'kosher salt',
  'lasagne noodles',
  'lean bacon',
  'leek',
  'lemon',
  'lemon juice',
  'lemon peel',
  'light olive oil',
  'lime',
  'lime juice',
  'lime peel',
  'long grain rice',
  'low sodium baking powder',
  'low sodium chicken broth',
  'lower sodium soy sauce',
  'lump crabmeat',
  'macadamia nuts',
  'maple extract',
  'maple flavoring',
  'maple syrup',
  'marinated artichokes',
  'mayonnaise',
  'medjool dates',
  'mesclun',
  'milk',
  'milk chocolate',
  'mini chocolate chips',
  'mini peppers',
  'mint',
  'miso',
  'molasses',
  'monterey jack cheese',
  'mozzarella',
  'mustard powder',
  'nutmeg',
  'oat bran',
  'olive oil',
  'onion',
  'onion powder',
  'orange juice',
  'orange zest',
  'oregano',
  'oreo cookies',
  'orzo',
  'palm sugar',
  'pancetta',
  'panko',
  'parmesan',
  'parsley',
  'peanut butter',
  'peas and carrots',
  'pecans',
  'pecorino romano',
  'peppermint extract',
  'pepperoni',
  'peppers',
  'persian cucumber',
  'petite peas',
  'pickled jalapenos',
  'pine nuts',
  'pineapple juice',
  'pinto beans',
  'pistachio nuts',
  'pizza dough',
  'plain greek yogurt',
  'plain yogurt',
  'poppy seeds',
  'pork ribs',
  'pork sausage',
  'portobello mushrooms',
  'potato',
  'powdered sugar',
  'provolone',
  'puff pastry dough',
  'pumpkin pie spice',
  'quark',
  'quick cooking oats',
  'quinoa',
  'raisins',
  'ranch dressing',
  'red onion',
  'red pepper',
  'red pepper flakes',
  'reduced fat cream cheese',
  'refried beans',
  'refrigerated crescent rolls',
  'refrigerated pie crust',
  'rice',
  'ricotta cheese',
  'roasted red peppers',
  'rolled oats',
  'romanesco',
  'root vegetable',
  'russet potato',
  'sage',
  'salami',
  'salt and pepper',
  'salted butter',
  'sausage',
  'savoy cabbage',
  'scotch whiskey',
  'seafood seasoning',
  'semisweet chocolate',
  'semisweet chocolate chips',
  'serrano pepper',
  'shallot',
  'sharp cheddar cheese',
  'sherry',
  'shortcrust pastry',
  'shortening',
  'shredded cheddar cheese',
  'shredded cheese',
  'shredded mozzarella',
  'silken tofu',
  'smoked paprika',
  'sour cream',
  'soy buttery spread',
  'soymilk',
  'spanish chorizo',
  'sparkling water',
  'spinach',
  'spinach fettuccine',
  'spring onions',
  'sriracha',
  'strawberries',
  'sub bun',
  'sugar',
  'sun dried tomatoes',
  'sunflower seeds',
  'sweet potato',
  'sweetened condensed milk',
  'swiss chard',
  'swiss cheese',
  'table salt',
  'table syrup',
  'tapioca starch',
  'tarragon',
  'tea',
  'thin baguette',
  'thyme',
  'tomato',
  'tomato juice',
  'tomato paste',
  'turbinado sugar',
  'unbleached all purpose flour',
  'unbleached flour',
  'unsalted butter',
  'unsweetened coconut',
  'unsweetened shredded coconut',
  'vanilla extract',
  'vanilla paste',
  'vanilla powder',
  'vanilla yogurt',
  'vegetable stock',
  'walnuts',
  'water',
  'wheat flour',
  'whipped topping',
  'whipping cream',
  'white bread',
  'white chocolate chips',
  'white onion',
  'white pepper',
  'white potato',
  'white whole wheat flour',
  'white wine vinegar',
  'whole chicken',
  'whole kernel corn',
  'whole turkey',
  'whole wheat flour',
  'whole wheat pastry flour',
  'worcestershire sauce',
  'yellow onion',
  'yogurt',
  'yukon gold potato',
  'zucchini',
];

export const EMPTY_MESSAGE = "You haven't added anything yet...";
